---
title: "EWMA prices"
author: "Jerzy Pawlowski"
affiliation: NYU Tandon School of Engineering
email: jp3900@nyu.edu
date: '`r format(Sys.time(), "%m/%d/%Y")`'
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
# this is a setup chunk run only once at start of shiny
knitr::opts_chunk$set(echo=FALSE)
# load package 
library(shiny)
library(quantmod)
# set look-back interval for averaging
inter_val <- 31
# calculate close prices
cl_ose <- quantmod::Cl(rutils::env_etf$VTI["2008/2009"])
# set plot_theme plot line colors
plot_theme <- chart_theme()
plot_theme$col$line.col <- c("orange", "blue")
```

```{r ewma_model, echo=FALSE}
inputPanel(
  sliderInput("lamb_da", label="lambda:",
    min=0.01, max=1.0, value=0.3, step=0.1)
)  # end inputPanel

renderPlot({
  
  # get EWMA decay parameter from input
  lamb_da <- input$lamb_da
  # calculate EWMA prices
  weight_s <- exp(lamb_da*1:inter_val)
  weight_s <- weight_s/sum(weight_s)
  ew_ma <- filter(cl_ose, filter=rev(weight_s), sides=1)
  ew_ma[1:(inter_val-1)] <- ew_ma[inter_val]
  ew_ma <- xts(cbind(cl_ose, ew_ma), order.by=index(cl_ose))
  colnames(ew_ma) <- c("VTI", "VTI EWMA")
  # plot EWMA prices
  plot(chart_Series(ew_ma, theme=plot_theme, name="EWMA prices"))
  legend("top", legend=colnames(ew_ma),
         inset=0.1, bg="white", lty=c(1, 1), lwd=c(6, 6),
         col=plot_theme$col$line.col, bty="n")
  
})  # end renderPlot
```
